title: Codebreaker
hero_image: images/banner.png
description: Analyse a frequency graph to crack the code, whilst learning about lists and functions.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Encode the alphabet
  - title: Encode a message
  - title: Encode text from a file
  - title: Create frequency analyser
  - title: Analyse the frequency
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: What next?
